In [1]:
import pandas as pd

In [4]:
import pandas as pd
n=int(input("enter a number"))
elements=[]
for i in range(n):
    values=int(input("enter a elements"))
    elements.append(values)
series=pd.Series( elements)
series

enter a number 3
enter a elements 1
enter a elements 2
enter a elements 3

0    1
1    2
2    3
dtype: int64

In [6]:
n=int(input("enter a number of students"))
names=[]
marks=[]
for i in range(n):
     name=input("enter a students name")
     mark=int(input("enterr a marks") )
     names.append(name)
     marks.append(mark)

series=pd.Series(names)
series=pd.Series(marks)    
series

enter a number of students 3
enter a students name lily
enterr a marks 67
enter a students name sily
enterr a marks 89
enter a students name tony
enterr a marks 45

0    67
1    89
2    45
dtype: int64

In [7]:
import pandas as pd
n=int(input("enter a  no of students"))
rollno=[]
name=[]
age=[]
marks=[]
for i in range(n):
    roll=int(input("enter a rollno"))
    rollno.append(roll)
    names=input("enter a names")
    name.append(names)
    ages=int(input("enter a age"))
    age.append(ages)
    mark=int(input("enterr a marks") )       
    marks.append(mark) 
    
df = pd.DataFrame({
    "Roll No": rollno,
    "Name": name,
    "Age": age,
    "Marks": marks
})
df

enter a  no of students 3
enter a rollno 1
enter a names lily
enter a age 17
enterr a marks 89
enter a rollno 2
enter a names sily
enter a age 18
enterr a marks 68
enter a rollno 3
enter a names tony
enter a age 18
enterr a marks 69

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68
2        3  tony   18     69

In [8]:
df.head(2)

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68

In [ ]:
df.tail(2)

In [9]:
df.shape

(3, 4)

In [ ]:
df.info

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll No  3 non-null      int64
 1   Name     3 non-null      object
 2   Age      3 non-null      int64
 3   Marks    3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.columns

In [11]:
df.dtypes

Roll No     int64
Name       object
Age         int64
Marks       int64
dtype: object

In [12]:
df.describe()

       Roll No        Age      Marks
count      3.0   3.000000   3.000000
mean       2.0  17.666667  75.333333
std        1.0   0.577350  11.846237
min        1.0  17.000000  68.000000
25%        1.5  17.500000  68.500000
50%        2.0  18.000000  69.000000
75%        2.5  18.000000  79.000000
max        3.0  18.000000  89.000000

In [13]:
df.iloc[:,1]

0    lily
1    sily
2    tony
Name: Name, dtype: object

In [14]:
print(df.iloc[:,3])

0    89
1    68
2    69
Name: Marks, dtype: int64

In [15]:
print(df.iloc[:, [1, 3]])

   Name  Marks
0  lily     89
1  sily     68
2  tony     69

In [16]:
df["Name"]

0    lily
1    sily
2    tony
Name: Name, dtype: object

In [17]:
df["Marks"]

0    89
1    68
2    69
Name: Marks, dtype: int64

In [18]:
df.loc[:0]

   Roll No  Name  Age  Marks
0        1  lily   17     89

In [19]:
df.loc[:2]

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68
2        3  tony   18     69

In [20]:
df.iloc[-3:]

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68
2        3  tony   18     69

In [21]:


df.loc[0]

Roll No       1
Name       lily
Age          17
Marks        89
Name: 0, dtype: object

In [22]:
df.loc[2]

Roll No       3
Name       tony
Age          18
Marks        69
Name: 2, dtype: object

#filtering

In [23]:
df[df["Marks"]>75]

   Roll No  Name  Age  Marks
0        1  lily   17     89

In [24]:
df[df["Age"]>18]

Empty DataFrame
Columns: [Roll No, Name, Age, Marks]
Index: []

In [25]:
df[(df["Marks"]>65)& (df["Marks"]<=100)]

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68
2        3  tony   18     69

In [26]:
df[df["Marks"]<df["Marks"].mean()]

   Roll No  Name  Age  Marks
1        2  sily   18     68
2        3  tony   18     69

#ADD AND delete columns

In [27]:
grades = []

for i in range(n):
    grade = input("Enter grade: ")
    grades.append(grade)

df["Grade"] = grades

print(df)

Enter grade:  A
Enter grade:  b
Enter grade:  C

   Roll No  Name  Age  Marks Grade
0        1  lily   17     89     A
1        2  sily   18     68     b
2        3  tony   18     69     C

In [28]:
df.drop("Grade", axis=1, inplace=True)

print(df)

   Roll No  Name  Age  Marks
0        1  lily   17     89
1        2  sily   18     68
2        3  tony   18     69

In [29]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Aman", "Sneha", "Riya"],
    "Marks": [85, None, 72, None, 90]
})
df

    Name  Marks
0  Rahul   85.0
1  Priya    NaN
2   Aman   72.0
3  Sneha    NaN
4   Riya   90.0

In [30]:
print(df.isnull())

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False

In [31]:
print(df.isnull().sum())

Name     0
Marks    2
dtype: int64

In [32]:
df.dropna()

    Name  Marks
0  Rahul   85.0
2   Aman   72.0
4   Riya   90.0

In [33]:
df.fillna(0)

    Name  Marks
0  Rahul   85.0
1  Priya    0.0
2   Aman   72.0
3  Sneha    0.0
4   Riya   90.0

sorting

In [34]:
df.sort_values("Marks",ascending=True)

    Name  Marks
2   Aman   72.0
0  Rahul   85.0
4   Riya   90.0
1  Priya    NaN
3  Sneha    NaN

In [35]:
df.sort_values("Name")

    Name  Marks
2   Aman   72.0
1  Priya    NaN
0  Rahul   85.0
4   Riya   90.0
3  Sneha    NaN

In [36]:
df.sort_values("Marks",ascending=False)

    Name  Marks
4   Riya   90.0
0  Rahul   85.0
2   Aman   72.0
1  Priya    NaN
3  Sneha    NaN

#group by



#aggregation function

In [38]:

print("Highest Marks:", df["Marks"].max())

Highest Marks: 90.0

In [39]:
df["Marks"].sum()

np.float64(247.0)

In [40]:
df["Marks"].mean()

np.float64(82.33333333333333)

In [42]:
df["Marks"].min()

72.0

In [43]:
df["Marks"].count()

np.int64(3)

In [51]:
n=int(input("enter a  no of employee"))
employee=[]
department=[]
salary=[]
for i in range(n):
    name=input("enter a name of employe")
    employee.append(name)
    departments=input("enter a department")
    department.append(departments)
    amount=int(input("enetr a salary"))
    salary.append(amount)
    
df=pd.DataFrame({
    "employee name": employee,
    "department":department,
    "salary":salary
    
})
df

enter a  no of employee 3
enter a name of employe lily
enter a department prouduct
enetr a salary 10000000
enter a name of employe sily
enter a department software
enetr a salary 20000000
enter a name of employe tony
enter a department testing
enetr a salary 50000

  employee name department    salary
0          lily   prouduct  10000000
1          sily   software  20000000
2          tony    testing     50000

In [54]:
df.groupby("department")["salary"].mean()

department
prouduct    10000000.0
software    20000000.0
testing        50000.0
Name: salary, dtype: float64

In [55]:
df.groupby("department")["salary"].max()

department
prouduct    10000000
software    20000000
testing        50000
Name: salary, dtype: int64

In [56]:
df.groupby("department")["salary"].min()

department
prouduct    10000000
software    20000000
testing        50000
Name: salary, dtype: int64